### ISSUE TITLE
Add sentence or two about filtering long utterances

### ISSUE THREAD

**Issue by futurulus** [futurulus/coop-nets#18]
One quick todo (from @ngoodman) remaining. @hawkrobe, any chance you would write a sentence or two for this?

https://github.com/futurulus/coop-nets/blob/5b2cc9/writing/2016/tacl_colors.tex#L344: "need to say something about these long utterances, maybe in a footnote. eg how many there were, why they were excluded..."

**Comment by hawkrobe** [comment]
will do!
